// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _22._10._23_INMN3_PA1._1.Data;

#nullable disable

namespace _22._10._23_INMN3_PA1._1.Migrations
{
    [DbContext(typeof(_22_10_23_INMN3_PA1_1Context))]
    partial class _22_10_23_INMN3_PA1_1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_22._10._23_INMN3_PA1._1.Models.Państwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataZałożenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Populacja")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Powierzchnia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Stolica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Państwa");
                });
#pragma warning restore 612, 618
        }
    }
}
